### PR TITLE
fix cargo warnings and compile error with rust 1.33

### PR DESCRIPTION
**Pull request by MightyPork**

### CODE REVIEW

**Comment by Mange** [comment]
Thank you for the PR. :heart: 

Unfortunately, your changes would bump up the minimum required version of Rust and I'd like to avoid that for a patch release.
I'm going to close this and repeat my fix from the 2.0 branch, where I made the uses of `DurationExtensions` more explicit.

I will credit you in the changelog still if you want as the main value of actually reporting this problem is not lost on me, and I want to credit you for your time spent working on this.

**Comment by MightyPork** [comment]
ah well, it's alright, I just want to be able to compile my [spotify genre blocker](https://git.ondrovo.com/MightyPork/rapblock) again without forking. hope you find time for it soon :`)

**Comment by Mange** [comment]
That's a cool project! I might use it myself to block a handful of artists that seem to always show up in my Daily Mixes and artist radios.

I'm pushing 1.1.2 right now, so you should be able to keep working on it hopefully!

[EDIT]: [It's out now.](https://crates.io/crates/mpris/1.1.2)

**Comment by MightyPork** [comment]
works great, thanks!

**Pull request closed without merging**
